### ISSUE TITLE
Configurations of the Facebook webhook

### ISSUE THREAD

**Issue by bernardofn** [MicrosoftContentModerator/samples-fbPageModeration#1]
I am following the tutorial. In step "Configure the Facebook page and App"
I can't go further than this: "Provide the FBListener Url as the Callback URL and the Verify Token you configured under the Function App Settings".

When configuring the app, FB gives me this error message: 

![image](https://user-images.githubusercontent.com/29437665/31729837-7cc972a6-b430-11e7-9662-5fdc7c079c2e.png)

Is this url the one I get here?
![image](https://user-images.githubusercontent.com/29437665/31729794-57029728-b430-11e7-89b1-f7be030f6e29.png)

And for the settings, how do I input the region? West Europe or westeurope?

**Comment by swiftarrow11** [comment]
Hi Bernardo,

The Verify Token that you have specified as "test" on the facebook side, must match with the application setting value of  "fb:VerificationToken" that you would have provisioned on the Azure Function side.

Facebook sends a request to the callback url (i.e. your FbListener URL) with the Token specified as "test". The FBListener checks if the token that came along with the request matches with the "fb:VerificationToken" value specified in the App Settings. If the value doesn't match, then the FBListener returns a http 401 response.
Please set the same value of this token on both sides, that should unblock you.

Let us know if you still face issues setting this up.
